### ISSUE TITLE
build compatibility with new DAGMC subrepo for PyNE

### ISSUE THREAD

**Issue by bam241** [svalinn/DAGMC-Trelis#106]
We seem to have problem with the new DAGMC way to deal with PyNE on MACOS....

new amalgamation and git subrepo might require some adjustment.

I spotted a problem at least for MacOS

**Comment by pshriwise** [comment]
What error is it giving you?

**Comment by bam241** [comment]
was just a python2-3 error
I fixed it with svalinn/dagmc#773

this can be closed now :)
