### ISSUE TITLE
Segfault on Centos 8

### ISSUE THREAD

**Issue by ondrejch** [svalinn/DAGMC-Trelis#108]
Hi, all builds fine and installs just copy-pasting the install scripts. 
After installation, Cubit segfaults with the below. Any ideas? Thanks.

$ coreform_cubit 
[2021-07-23 22:18:48.378] [info] RLM session initialized
Supervisor::Impl::load_plugins: Loaded component: libcoreformcae.ccg from directory: /opt/Coreform-Cubit-2021.5/bin
Supervisor::Impl::load_plugins: Loaded component: libcubitcomp.ccl from directory: /opt/Coreform-Cubit-2021.5/bin
Supervisor::Impl::load_plugins: Loaded component: libcubitcompgui.ccg from directory: /opt/Coreform-Cubit-2021.5/bin
Supervisor::Impl::load_plugins: Loaded component: libflexcomp.ccl from directory: /opt/Coreform-Cubit-2021.5/bin
Supervisor::Impl::load_plugins: Loaded component: libflexgui.ccg from directory: /opt/Coreform-Cubit-2021.5/bin
Loaded Svalinn plugin.

-- DAGMC export command available.
...Interrupt Detected. CUBIT Exiting...
Segmentation fault (core dumped)

**Comment by makeclean** [comment]
HI @ondrejch could you report what ldd libsvalinn_plugin.so gives? I recently found a linking issue with the plugin but don't have a fix yet.

**Comment by ondrejch** [comment]
Hi @makeclean, it seems all dynamic libraries are linked: 

$ ldd libsvalinn_plugin.so 
ldd: warning: you do not have execution permission for `./libsvalinn_plugin.so'
	linux-vdso.so.1 (0x00007fffa8b44000)
	libcubiti19.so => /opt/Coreform-Cubit-2021.5/bin/libcubiti19.so (0x00007ffa1074a000)
	libMOAB.so.0 (0x00007ffa1014d000)
	libdagmc.so (0x00007ffa0fedd000)
	libpyne_dagmc.so (0x00007ffa0fa9b000)
	libuwuw.so (0x00007ffa0f845000)
	libmakeWatertight.so (0x00007ffa0f5c1000)
	libmcnp2cad.so (0x00007ffa0f00a000)
	libiGeom.so (0x00007ffa0ed9b000)
	libcubit_geom.so => /opt/Coreform-Cubit-2021.5/bin/libcubit_geom.so (0x00007ffa0e986000)
	libcubit_util.so => /opt/Coreform-Cubit-2021.5/bin/libcubit_util.so (0x00007ffa0e741000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffa0e521000)
	libstdc++.so.6 => /opt/Coreform-Cubit-2021.5/bin/libstdc++.so.6 (0x00007ffa0e2f1000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ffa0df6f000)
	libgcc_s.so.1 => /opt/Coreform-Cubit-2021.5/bin/libgcc_s.so.1 (0x00007ffa14a5f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ffa0dbaa000)
	libgtcAttrib.so => /opt/Coreform-Cubit-2021.5/bin/./libgtcAttrib.so (0x00007ffa14a3d000)
	libSpaACIS.so => /opt/Coreform-Cubit-2021.5/bin/./libSpaACIS.so (0x00007ffa0a0c7000)
	libmg-cvm.so => /opt/Coreform-Cubit-2021.5/bin/./libmg-cvm.so (0x00007ffa09dc2000)
	libmg-adapt.so => /opt/Coreform-Cubit-2021.5/bin/./libmg-adapt.so (0x00007ffa14909000)
	libmg-tetra.so => /opt/Coreform-Cubit-2021.5/bin/./libmg-tetra.so (0x00007ffa09916000)
	libmg-surfopt.so => /opt/Coreform-Cubit-2021.5/bin/./libmg-surfopt.so (0x00007ffa09730000)
	libmg-cadsurf.so => /opt/Coreform-Cubit-2021.5/bin/./libmg-cadsurf.so (0x00007ffa09386000)
	libmeshgems_stubs.so => /opt/Coreform-Cubit-2021.5/bin/./libmeshgems_stubs.so (0x00007ffa09282000)
	liblpsolve55.so => /opt/Coreform-Cubit-2021.5/bin/./liblpsolve55.so (0x00007ffa091c4000)
	libmeshgems.so => /opt/Coreform-Cubit-2021.5/bin/./libmeshgems.so (0x00007ffa08f99000)
	libcubit_sizing_source.so => /opt/Coreform-Cubit-2021.5/bin/./libcubit_sizing_source.so (0x00007ffa148f5000)
	libshowviz_cubit.so => /opt/Coreform-Cubit-2021.5/bin/./libshowviz_cubit.so (0x00007ffa08ec8000)
	libshowviz_sim.so => /opt/Coreform-Cubit-2021.5/bin/./libshowviz_sim.so (0x00007ffa08e4a000)
	libshowviz_mesh.so => /opt/Coreform-Cubit-2021.5/bin/./libshowviz_mesh.so (0x00007ffa08dd8000)
	libshowviz_geom.so => /opt/Coreform-Cubit-2021.5/bin/./libshowviz_geom.so (0x00007ffa08d6e000)
	libshowviz_base.so => /opt/Coreform-Cubit-2021.5/bin/./libshowviz_base.so (0x00007ffa08c89000)
	libvtkCommonCore-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./libvtkCommonCore-8.2.so.1 (0x00007ffa086c6000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007ffa08383000)
	libmesquite.so => /opt/Coreform-Cubit-2021.5/bin/./libmesquite.so (0x00007ffa0817a000)
	libSPAIInterop.so => /opt/Coreform-Cubit-2021.5/bin/./libSPAIInterop.so (0x00007ffa07f35000)
	libSPAIAcis.so => /opt/Coreform-Cubit-2021.5/bin/./libSPAIAcis.so (0x00007ffa07d1f000)
	libSPAIop.so => /opt/Coreform-Cubit-2021.5/bin/./libSPAIop.so (0x00007ffa0784c000)
	libmpi.so.40 => /opt/Coreform-Cubit-2021.5/bin/./libmpi.so.40 (0x00007ffa075e9000)
	libcubit_smd.so => /opt/Coreform-Cubit-2021.5/bin/./libcubit_smd.so (0x00007ffa07582000)
	libtrelis_lm.so => /opt/Coreform-Cubit-2021.5/bin/./libtrelis_lm.so (0x00007ffa07442000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ffa0723e000)
	libQt5Core.so.5 => /opt/Coreform-Cubit-2021.5/bin/./libQt5Core.so.5 (0x00007ffa04c8f000)
	libverdict.so.1.3 => /opt/Coreform-Cubit-2021.5/bin/./libverdict.so.1.3 (0x00007ffa148a5000)
	libhdf5.so.200 => /opt/Coreform-Cubit-2021.5/bin/./libhdf5.so.200 (0x00007ffa04646000)
	libhdf5_hl.so.200 => /opt/Coreform-Cubit-2021.5/bin/./libhdf5_hl.so.200 (0x00007ffa0460e000)
	libz.so.1 => /opt/Coreform-Cubit-2021.5/bin/./libz.so.1 (0x00007ffa043c2000)
	libpamgen.so => /opt/Coreform-Cubit-2021.5/bin/./libpamgen.so (0x00007ffa04283000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffa14870000)
	libhdf5_hl.so.100 => /lib64/libhdf5_hl.so.100 (0x00007ffa0405f000)
	libhdf5.so.103 => /lib64/libhdf5.so.103 (0x00007ffa03ad4000)
	libsz.so.2 => /lib64/libsz.so.2 (0x00007ffa038d1000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ffa036c9000)
	libvtkRenderingOpenGL2-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkRenderingOpenGL2-8.2.so.1 (0x00007ffa0332b000)
	libvtkglew-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkglew-8.2.so.1 (0x00007ffa031cf000)
	libvtkInteractionWidgets-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkInteractionWidgets-8.2.so.1 (0x00007ffa02d38000)
	libvtkFiltersVerdict-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkFiltersVerdict-8.2.so.1 (0x00007ffa02cef000)
	libXt.so.6 => /lib64/libXt.so.6 (0x00007ffa02a84000)
	libSM.so.6 => /opt/Coreform-Cubit-2021.5/bin/././libSM.so.6 (0x00007ffa02877000)
	libICE.so.6 => /opt/Coreform-Cubit-2021.5/bin/././libICE.so.6 (0x00007ffa02651000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007ffa0243e000)
	libvtkRenderingCore-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkRenderingCore-8.2.so.1 (0x00007ffa02086000)
	libvtkFiltersSources-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkFiltersSources-8.2.so.1 (0x00007ffa01f53000)
	libvtkFiltersGeneral-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkFiltersGeneral-8.2.so.1 (0x00007ffa01ab2000)
	libvtkFiltersCore-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkFiltersCore-8.2.so.1 (0x00007ffa0141f000)
	libvtkCommonExecutionModel-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkCommonExecutionModel-8.2.so.1 (0x00007ffa012a1000)
	libvtkCommonDataModel-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkCommonDataModel-8.2.so.1 (0x00007ffa00c54000)
	libvtkCommonTransforms-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkCommonTransforms-8.2.so.1 (0x00007ffa00bf6000)
	libvtkCommonMisc-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkCommonMisc-8.2.so.1 (0x00007ffa00bc2000)
	libvtkCommonMath-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkCommonMath-8.2.so.1 (0x00007ffa00b45000)
	libvtkverdict-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkverdict-8.2.so.1 (0x00007ffa00afc000)
	libvtkRenderingLabel-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkRenderingLabel-8.2.so.1 (0x00007ffa00a1e000)
	libvtkFiltersModeling-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkFiltersModeling-8.2.so.1 (0x00007ffa0091e000)
	libvtkFiltersExtraction-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkFiltersExtraction-8.2.so.1 (0x00007ffa007a3000)
	libvtkRenderingFreeType-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkRenderingFreeType-8.2.so.1 (0x00007ffa006c3000)
	libvtkfreetype-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkfreetype-8.2.so.1 (0x00007ffa00620000)
	libvtkzlib-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkzlib-8.2.so.1 (0x00007ffa005fc000)
	libvtkRenderingAnnotation-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkRenderingAnnotation-8.2.so.1 (0x00007ffa003fb000)
	libGLU.so.1 => /lib64/libGLU.so.1 (0x00007ffa00189000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007ff9fff03000)
	libvtkInteractionStyle-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkInteractionStyle-8.2.so.1 (0x00007ff9ffe61000)
	libvtkIOImage-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkIOImage-8.2.so.1 (0x00007ff9ffc55000)
	libvtkFiltersGeometry-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkFiltersGeometry-8.2.so.1 (0x00007ff9ffb69000)
	libvtkCommonSystem-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtkCommonSystem-8.2.so.1 (0x00007ff9ffb3c000)
	libvtksys-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libvtksys-8.2.so.1 (0x00007ff9ffa76000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007ff9ff84d000)
	libSPAIInteropC.so => /opt/Coreform-Cubit-2021.5/bin/././libSPAIInteropC.so (0x00007ff9ff605000)
	libSPAIopC.so => /opt/Coreform-Cubit-2021.5/bin/././libSPAIopC.so (0x00007ff9ff229000)
	libSPAIopAcisC.so => /opt/Coreform-Cubit-2021.5/bin/././libSPAIopAcisC.so (0x00007ff9ff013000)
	libopen-rte.so.40 => /opt/Coreform-Cubit-2021.5/bin/././libopen-rte.so.40 (0x00007ff9fee94000)
	libopen-pal.so.40 => /opt/Coreform-Cubit-2021.5/bin/././libopen-pal.so.40 (0x00007ff9fec53000)
	libutil.so.1 => /opt/Coreform-Cubit-2021.5/bin/././libutil.so.1 (0x00007ff9fea40000)
	libcurl.so.4 => /opt/Coreform-Cubit-2021.5/bin/././libcurl.so.4 (0x00007ff9fe7a4000)
	libQt5Network.so.5 => /opt/Coreform-Cubit-2021.5/bin/././libQt5Network.so.5 (0x00007ff9fddc4000)
	libQt5Widgets.so.5 => /opt/Coreform-Cubit-2021.5/bin/././libQt5Widgets.so.5 (0x00007ff9fcd7f000)
	libQt5Gui.so.5 => /opt/Coreform-Cubit-2021.5/bin/././libQt5Gui.so.5 (0x00007ff9f9d83000)
	libicui18n.so.56 => /opt/Coreform-Cubit-2021.5/bin/././libicui18n.so.56 (0x00007ff9f9651000)
	libicuuc.so.56 => /opt/Coreform-Cubit-2021.5/bin/././libicuuc.so.56 (0x00007ff9f91b3000)
	libicudata.so.56 => /opt/Coreform-Cubit-2021.5/bin/././libicudata.so.56 (0x00007ff9f5fe5000)
	libgthread-2.0.so.0 => /opt/Coreform-Cubit-2021.5/bin/././libgthread-2.0.so.0 (0x00007ff9f5dd7000)
	libglib-2.0.so.0 => /opt/Coreform-Cubit-2021.5/bin/././libglib-2.0.so.0 (0x00007ff9f59ed000)
	libaec.so.0 => /lib64/libaec.so.0 (0x00007ff9f57e5000)
	libOpenGL.so.0 => /lib64/libOpenGL.so.0 (0x00007ff9f55b9000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007ff9f5387000)
	libvtkFiltersHybrid-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkFiltersHybrid-8.2.so.1 (0x00007ff9f5219000)
	libvtkImagingGeneral-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkImagingGeneral-8.2.so.1 (0x00007ff9f50d4000)
	libvtkImagingHybrid-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkImagingHybrid-8.2.so.1 (0x00007ff9f5020000)
	libvtkRenderingVolume-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkRenderingVolume-8.2.so.1 (0x00007ff9f4a57000)
	libvtkImagingColor-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkImagingColor-8.2.so.1 (0x00007ff9f49d7000)
	libvtkCommonComputationalGeometry-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkCommonComputationalGeometry-8.2.so.1 (0x00007ff9f496e000)
	libvtkImagingCore-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkImagingCore-8.2.so.1 (0x00007ff9f46b5000)
	libuuid.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libuuid.so.1 (0x00007ff9f44a7000)
	libvtkCommonColor-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkCommonColor-8.2.so.1 (0x00007ff9f4472000)
	libvtkFiltersStatistics-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkFiltersStatistics-8.2.so.1 (0x00007ff9f435b000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007ff9f40a5000)
	libvtkDICOMParser-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkDICOMParser-8.2.so.1 (0x00007ff9f4074000)
	libvtkmetaio-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkmetaio-8.2.so.1 (0x00007ff9f3f48000)
	libvtkpng-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkpng-8.2.so.1 (0x00007ff9f3eed000)
	libvtktiff-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtktiff-8.2.so.1 (0x00007ff9f3e59000)
	libvtkjpeg-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libvtkjpeg-8.2.so.1 (0x00007ff9f3dea000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007ff9f3be4000)
	libSPAXCommon.so => /opt/Coreform-Cubit-2021.5/bin/./././libSPAXCommon.so (0x00007ff9f39cf000)
	libSPAXBase.so => /opt/Coreform-Cubit-2021.5/bin/./././libSPAXBase.so (0x00007ff9f3588000)
	libSPAXInterop.so => /opt/Coreform-Cubit-2021.5/bin/./././libSPAXInterop.so (0x00007ff9f328c000)
	libSPAXBoundaryRep.so => /opt/Coreform-Cubit-2021.5/bin/./././libSPAXBoundaryRep.so (0x00007ff9f2fe7000)
	libSPAXIop.so => /opt/Coreform-Cubit-2021.5/bin/./././libSPAXIop.so (0x00007ff9f2ada000)
	libSPAXIopAcis.so => /opt/Coreform-Cubit-2021.5/bin/./././libSPAXIopAcis.so (0x00007ff9f288c000)
	libnghttp2.so.14 => /opt/Coreform-Cubit-2021.5/bin/./././libnghttp2.so.14 (0x00007ff9f2661000)
	libssh2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libssh2.so.1 (0x00007ff9f2411000)
	libmbedtls.so.13 => /opt/Coreform-Cubit-2021.5/bin/./././libmbedtls.so.13 (0x00007ff9f21b3000)
	libmbedx509.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libmbedx509.so.1 (0x00007ff9f1f74000)
	libmbedcrypto.so.5 => /opt/Coreform-Cubit-2021.5/bin/./././libmbedcrypto.so.5 (0x00007ff9f1ccc000)
	libgssapi_krb5.so.2 => /opt/Coreform-Cubit-2021.5/bin/./././libgssapi_krb5.so.2 (0x00007ff9f1a64000)
	libpcre.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././libpcre.so.1 (0x00007ff9f17f8000)
	libvtkImagingSources-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././././libvtkImagingSources-8.2.so.1 (0x00007ff9f1787000)
	libvtkIOXML-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././././libvtkIOXML-8.2.so.1 (0x00007ff9f15d1000)
	libvtkIOXMLParser-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././././libvtkIOXMLParser-8.2.so.1 (0x00007ff9f15a3000)
	libvtkImagingFourier-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././././libvtkImagingFourier-8.2.so.1 (0x00007ff9f1557000)
	libSPAXicuC.so => /opt/Coreform-Cubit-2021.5/bin/././././libSPAXicuC.so (0x00007ff9f134b000)
	libSPAXGeometryRepresentation.so => /opt/Coreform-Cubit-2021.5/bin/././././libSPAXGeometryRepresentation.so (0x00007ff9f0f51000)
	libSPAXAssemblyRep.so => /opt/Coreform-Cubit-2021.5/bin/././././libSPAXAssemblyRep.so (0x00007ff9f0d19000)
	libSPAXVisualizationRep.so => /opt/Coreform-Cubit-2021.5/bin/././././libSPAXVisualizationRep.so (0x00007ff9f09fa000)
	libSPAXVisualizationAsm.so => /opt/Coreform-Cubit-2021.5/bin/././././libSPAXVisualizationAsm.so (0x00007ff9f07ce000)
	libSPAXPMIRep.so => /opt/Coreform-Cubit-2021.5/bin/././././libSPAXPMIRep.so (0x00007ff9f05a0000)
	libSPAXManufacturingRep.so => /opt/Coreform-Cubit-2021.5/bin/././././libSPAXManufacturingRep.so (0x00007ff9f038a000)
	libSPAXAcis.so => /opt/Coreform-Cubit-2021.5/bin/././././libSPAXAcis.so (0x00007ff9efeba000)
	libSPAXAcisBase.so => /opt/Coreform-Cubit-2021.5/bin/././././libSPAXAcisBase.so (0x00007ff9efc14000)
	libSPAXAcisManufacturingImporter.so => /opt/Coreform-Cubit-2021.5/bin/././././libSPAXAcisManufacturingImporter.so (0x00007ff9ef9ed000)
	libSPAXAcisPMIImporter.so => /opt/Coreform-Cubit-2021.5/bin/././././libSPAXAcisPMIImporter.so (0x00007ff9ef7a0000)
	libkrb5.so.3 => /opt/Coreform-Cubit-2021.5/bin/././././libkrb5.so.3 (0x00007ff9ef485000)
	libk5crypto.so.3 => /opt/Coreform-Cubit-2021.5/bin/././././libk5crypto.so.3 (0x00007ff9ef248000)
	libcom_err.so.2 => /opt/Coreform-Cubit-2021.5/bin/././././libcom_err.so.2 (0x00007ff9ef03b000)
	libkrb5support.so.0 => /opt/Coreform-Cubit-2021.5/bin/././././libkrb5support.so.0 (0x00007ff9eee25000)
	libkeyutils.so.1 => /opt/Coreform-Cubit-2021.5/bin/././././libkeyutils.so.1 (0x00007ff9eec1c000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007ff9eea05000)
	libvtkIOCore-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././././libvtkIOCore-8.2.so.1 (0x00007ff9ee94e000)
	libvtkexpat-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././././libvtkexpat-8.2.so.1 (0x00007ff9ee916000)
	libSPAXicuuc54.so => /opt/Coreform-Cubit-2021.5/bin/./././././libSPAXicuuc54.so (0x00007ff9ee4db000)
	libSPAXicuin54.so => /opt/Coreform-Cubit-2021.5/bin/./././././libSPAXicuin54.so (0x00007ff9ede85000)
	libSPAXicuio54.so => /opt/Coreform-Cubit-2021.5/bin/./././././libSPAXicuio54.so (0x00007ff9edc70000)
	libSPAXAcisKernel.so => /opt/Coreform-Cubit-2021.5/bin/./././././libSPAXAcisKernel.so (0x00007ff9eda4e000)
	libSPAXAcisMesh.so => /opt/Coreform-Cubit-2021.5/bin/./././././libSPAXAcisMesh.so (0x00007ff9ed83b000)
	libSPAXAcisPMIEntities.so => /opt/Coreform-Cubit-2021.5/bin/./././././libSPAXAcisPMIEntities.so (0x00007ff9ed5a8000)
	libselinux.so.1 => /opt/Coreform-Cubit-2021.5/bin/./././././libselinux.so.1 (0x00007ff9ed370000)
	libvtklz4-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././././././libvtklz4-8.2.so.1 (0x00007ff9ed340000)
	libvtklzma-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././././././libvtklzma-8.2.so.1 (0x00007ff9ed302000)
	libvtkdoubleconversion-8.2.so.1 => /opt/Coreform-Cubit-2021.5/bin/././././././libvtkdoubleconversion-8.2.so.1 (0x00007ff9ed2e3000)
	libicudt54.so => /opt/Coreform-Cubit-2021.5/bin/././././././libicudt54.so (0x00007ff9ea089000)

**Comment by dagmcci** [comment]
Could it be do to with that permission warning?

**Comment by ondrejch** [comment]
No. This is caused by the "chmod 644 *" step in the installation guide. It segfaults the same either way.

**Comment by bam241** [comment]
could you provide the exact command line you used to compile MOAB, DAGMC and the plugin ? (copy pasting from the script might not be enough, as there is variable set in the background....

mainly: 
```
CMAKE_ADDITIONAL_FLAGS="-DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0"
```

**Comment by bam241** [comment]
also may I ask who is behind @dagmcci  ?

**Comment by ondrejch** [comment]
> could you provide the exact command line you used to compile MOAB, DAGMC and the plugin ? (copy pasting from the script might not be enough, as there is variable set in the background....
> 
> mainly:
> 
> ```
> CMAKE_ADDITIONAL_FLAGS="-DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0"
> ```

I do hope I missed something :-) Here it is:


unset LD_LIBRARY_PATH
mkdir plugin-build
cd ${HOME}/plugin-build
mkdir -pv moab/bld
cd moab
git clone https://bitbucket.org/fathomteam/moab -b Version5.1.0
cd moab
autoreconf -fi
cd ../bld
../moab/configure CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 --enable-shared --enable-optimize --disable-debug --disable-blaslapack --with-eigen3=/usr/include/eigen3 --with-hdf5 --prefix=${HOME}/plugin-build/moab
make -j`grep -c processor /proc/cpuinfo
make install

cd ${HOME}/plugin-build
mkdir -pv DAGMC/bld
cd DAGMC
git clone https://github.com/svalinn/DAGMC -b develop
cd bld
cmake ../DAGMC -DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0                -DMOAB_DIR=${HOME}/plugin-build/moab                -DBUILD_UWUW=ON                -DBUILD_TALLY=OFF                -DBUILD_BUILD_OBB=OFF                -DBUILD_MAKE_WATERTIGHT=ON                -DBUILD_SHARED_LIBS=ON                -DBUILD_STATIC_LIBS=OFF                -DCMAKE_BUILD_TYPE=Release                -DCMAKE_INSTALL_PREFIX=${HOME}/plugin-build/DAGMC
make -j`grep -c processor /proc/cpuinfo
make install

cd ${HOME}/plugin-build
mkdir -pv bld
cd bld
make ../Cubit-plugin -DCUBIT_ROOT=/opt/Coreform-Cubit-2021.5/  -DDAGMC_DIR=${HOME}/plugin-build/DAGMC                        -DCMAKE_BUILD_TYPE=Release                        -DCMAKE_INSTALL_PREFIX=${HOME}/plugin-build
make -j`grep -c processor /proc/cpuinfo
make install

**Comment by bam241** [comment]
It seems That you are missing the ABI flag for the plug-in :)

**Comment by gonuke** [comment]
Is our documentation missing the ABI flag?

**Comment by bam241** [comment]
@gonuke yes the readme.md Is missing it :)

**Comment by ondrejch** [comment]
Woo, this worked :) Thanks Baptiste @bam241! Please add that to the Readme ;-)

cmake ../Cubit-plugin -DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 -DCUBIT_ROOT=/opt/Coreform-Cubit-2021.5/  -DDAGMC_DIR=${HOME}/plugin-build/DAGMC                        -DCMAKE_BUILD_TYPE=Release                        -DCMAKE_INSTALL_PREFIX=${HOME}/plugin-build

**Comment by bam241** [comment]
This seems to have been fixed. closing.

Feel free to re-open if this still occurs or you experience this again.
