### ISSUE TITLE
Cubit plugin in a Dockerfile glibc version error

### ISSUE THREAD

**Issue by shimwell** [svalinn/DAGMC-Trelis#112]
Let me know if this should be opened on the MOAB repo but I've stumbled across an error when installing the plugin within a few Dockerfiles

It appears that ```GLIBC_2.29``` is required by MOAB but this is not always available in the OS
continuumio/miniconda3:4.10.3 was published 12 days ago and comes with ```GLIBC_2.28``` and continuumio/miniconda3:4.9.2 which is the previous release also has ```GLIBC_2.28``` 

FROM continuumio/miniconda3:4.9.2
![Screenshot from 2021-08-04 21-05-03](https://user-images.githubusercontent.com/8583900/128250869-9deab3b9-9470-4f28-93bc-beeaa0d6da6a.png)

FROM continuumio/miniconda3:4.10.3 with a python 3.8 environment created as Cubit appears [to not support python 3.9](https://forum.coreform.com/t/python-3-9-support-in-cubit/1199)
![Screenshot from 2021-08-04 21-30-59](https://user-images.githubusercontent.com/8583900/128251032-3959bc28-bc76-4306-9984-09a41b4cb95d.png)

ubuntu:21.04 docker image also fails as it has glibc version 2.28-10

Wondering if anyone knows a work around for this

**Comment by bam241** [comment]
The problem might be related to your LD_LIBRARY_PATH, when running from command line I have to unset it....

**Comment by shimwell** [comment]
Had a quick go with setting the LD_LIBRARY_PATH to nothing. Looks like the same error occurs

this is with ubuntu 21.04 base image

![Screenshot from 2021-08-04 23-39-21](https://user-images.githubusercontent.com/8583900/128264564-41b5777f-dc3e-4c7a-bf99-a9ee060c592e.png)

**Comment by shimwell** [comment]
I'm thinking of adding a matrix to the build for different images as we have a few different glic versions

ubuntu 20.04 makes use of glibc 2.31
ubuntu 21.04 makes use of glibc 2.33
debian 10.10 makes use of glibc 2.28

**Comment by shimwell** [comment]
Just managed to get the Cubit plugin building for Debian 10.10
https://github.com/Shimwell/Cubit-plugin/runs/3279990398?check_suite_focus=true

**Comment by shimwell** [comment]
PR #115 should solve this issue

**Comment by shimwell** [comment]
Thanks everyone for helping with the PR #115 that solved this problem I was having.
