### ISSUE TITLE
Mac OS build failing on GH actions

### ISSUE THREAD

**Issue by shimwell** [svalinn/DAGMC-Trelis#120]
After triggering the recent release at the DAGMC meeting I noticed that the Mac OS builds failed

https://github.com/svalinn/Cubit-plugin/runs/3372537266?check_suite_focus=true

It failed on the DAGMC build with the message ```fatal error: too many errors emitted, stopping now [-ferror-limit=]```

**Comment by gonuke** [comment]
I'm pretty sure this is due to changes in DAGMC that is not being tested for MacOS

**Comment by gonuke** [comment]
An effort is underway to address this

**Comment by bam241** [comment]
this is fixed in both coming PR svalinn/dagmc#727 and svalinn/dagmc#780

DAGMC.cpp is missing and `#include <array>` I guess windows and Mac compile are less permissive than the linux ones :)

**Comment by bam241** [comment]
The fix has been merged svalinn/DAGMC#780.
I restarted the release action for Mac.
this should allow to upload the correct packages.
closing when everything is confirmed as passed

**Comment by bam241** [comment]
the Mac workflow worked as expected. closing.
