### ISSUE TITLE
Error storing surface senses

### ISSUE THREAD

**Issue by Itay-max** [svalinn/DAGMC-Trelis#126]
Hello
I am having trouble to export my geometry from cubit into a .h5m file format using dagmc.

I've came across this problem already in this [query](https://groups.google.com/g/dagmc-users/c/HIwohB36_Cg).
the problem might be overlapping.
If the problem is indeed caused by overlapping,  how can I fix it using cubit?

Anyway,
:here is the full log of the error
Cubit>export dagmc "test.h5m"

Setting faceting tolerance to 0.001

Setting length tolerance to 0

Setting normal tolerance to 5

Found 81822 entities of dimension 0

Found 135347 entities of dimension 1

Found 57301 entities of dimension 2

Found 958 entities of dimension 3

Surface 58831 has reverse sense with multiple volume 273 and volume 284

Error storing surface senses: 16

ERROR: Command Failed.

Any help will be appreciated.

Thanks.

**Comment by shimwell** [comment]
It might be worth trying the new overlapping tool that comes with DAGMC to check for overlaps.

To check for overlaps in the resulting h5m file one can use the DAGMC overlap checker. -p is the number of points to check on each line
```
conda install -c conda-forge dagmc
overlap_check dagmc.h5m -p 1000
```

**Comment by Itay-max** [comment]
Thank you for your reply.
I am still not able to export to h5m due to the error I mentioned.

**Comment by makeclean** [comment]
Hi @itayhorin please look at the following Cubit tutorial - https://coreform.com/downloads/lecture7-Power_ToolsPDF.pdf - it will tell you how to use 'PowerTools' when you click analyse it should show you overlapping volumes in the tree. You can go from there to figure out how to resolve overlaps, usually a combination of Boolean operations to remove the gross overlaps, or moving if there are allignment problems.

**Comment by Itay-max** [comment]
Thanks!
