### ISSUE TITLE
Resolve need for `register_attrib_type`

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC-Trelis#15]
Updates to CGM interface cause errors when trying to invoke `register_attrib_type` in `iGeom_funcs.cpp`.  It is not clear whether or not we need these lines at all since they are part of generic iGeom capability, but may not be used by us.

We need to understand its role in this code and then decide if we can do without it in our stripped down iGeom needs.

**Comment by gonuke** [comment]
If we deem it necessary, then create a new issue for contacting CSimSoft to resolve the interface change.

**Comment by pshriwise** [comment]
If I'm understanding the current state correctly, it sounds like we don't in that groups are named properly in Trelis for MCNP input decks with materials. 

One thing to verify is that these groups are exported properly using the `export dagmc` command. If this works, then I would consider the `register_attrib_type` call unecessary.

**Comment by ejwilson3** [comment]
How do I go about testing the .h5m file to make sure that the groups are properly exported?

**Comment by pshriwise** [comment]
The easiest way is to use MOAB's `mbsize` on the .h5m file. 

`mbsize -ll <.h5m_file> | grep NAME` should show you a list of the material names as they appear in Trelis.

**Comment by ejwilson3** [comment]
I think it's working.  That command on a file created from "INP-densities" returns 
    NAME = picked
    NAME = graveyard
    NAME = mat_1_rho_0.05
    EXTRA_NAME0 = mat_2_rho_-2
    EXTRA_NAME1 = mat_2_rho__2
    NAME = mat_2_rho_-2
which, as far as I can tell, fits with the input file.

**Comment by ejwilson3** [comment]
The plugin works as expected without calling 'register_attrib_type'.
