### ISSUE TITLE
Build from source make error in DAGMC - which versions?

### ISSUE THREAD

**Issue by rmchurch** [svalinn/DAGMC-Trelis#154]
I'm installing from source on RHEL following [these instructions](https://github.com/svalinn/Cubit-plugin/blob/develop/README_dev.md). It states to install MOAB 5.3.0 and DAGMC 3.2. The instructions though do `git clone` the develop branch of DAGMC. I run through, and get the below error. I try replacing develop with the v3.2.3 tag and get the same thing. Are these the right tags to be using? I confirm that the moab `include` path is being properly found in the cmake call. 

```
[ 26%] Linking CXX executable test_geom
/opt/rh/gcc-toolset-10/root/usr/bin/ld: CMakeFiles/overlap_check.dir/overlap_check.cpp.o: in function `main':
overlap_check.cpp:(.text.startup+0x8f): undefined reference to `ProgOptions::ProgOptions(std::string const&, std::string const&)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: overlap_check.cpp:(.text.startup+0x130): undefined reference to `void ProgOptions::addRequiredArg<std::string>(std::string const&, std::string const&, std::string*, int)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: overlap_check.cpp:(.text.startup+0x1b2): undefined reference to `void ProgOptions::addOpt<int>(std::string const&, std::string const&, int*, int)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: overlap_check.cpp:(.text.startup+0x234): undefined reference to `void ProgOptions::addOpt<int>(std::string const&, std::string const&, int*, int)'
```

**Comment by ahnaf-tahmid-chowdhury** [comment]
Hello @rmchurch, I noticed you're encountering difficulties installing DAGMC. It appears you might be following instructions that are three years old. We're currently in the process of updating our documentation, and the revised versions will be available soon. In the meantime, if you're comfortable with Docker, you can refer to the following CI [workflow](https://github.com/svalinn/DAGMC/blob/develop/CI/Dockerfile) instructions to install DAGMC.

Please note, our instructions are typically designed for Debian-based distributions (as I know). Given that RHEL is based on the Fedora distribution, you may encounter issues with using `apt` commands here. It would be beneficial for you to conduct some research to identify the corresponding dependencies needed for the DAGMC build in this context.

**Comment by gonuke** [comment]
I think you decided not to build this plugin, right @rmchurch and are using the one provided in Coreform Cubit?  Can we close this? We probably need to update the README to make it clear that this project will not be supported as a standalone plugin going forward.

**Comment by rmchurch** [comment]
Yes, I am using the Coreform Cubit plugin, so this can be closed.
