### ISSUE TITLE
Create minimal iGeom implementation

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC-Trelis#4]
Cut out all unnecessary functions and data types from iBase and iGeom, leaving only those necessary for MCNP2CAD (https://cnerg.slack.com/files/shriwise/F1D43F0J0/list_of_igeom_functions_used_by_mcnp2cad.txt)

**Comment by gonuke** [comment]
Can @ejwilson3 comment on this - can we consider it closed?  either complete or deemed unnecessary?  Other comments?

**Comment by ejwilson3** [comment]
Like issue #2 I believe this is completed.

**Comment by ejwilson3** [comment]
The plugin has a minimal iGeom implementation - it's still called iGeom and still uses `iBase_EntityHandle`s, but it works.
