### ISSUE TITLE
Build iGeom separately from CGM

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC-Trelis#5]
Currently, iGeom is built as part of the normal process of building CGMA (by default?).  It should be possible to decouple these, building iGeom as a standalone library, linked to an already build CGMA that is built without iGeom.

**Comment by gonuke** [comment]
Consider just moving current itaps files to a different location and building against their full implementation and against a CGM that may have iGeom turned off???

**Comment by gonuke** [comment]
Can @ejwilson3 comment on this - can we consider it closed?  either complete or deemed unnecessary?  Other comments?

**Comment by ejwilson3** [comment]
I think this should be complete; I don't have it built as a standalone library, but have it inside of the mcnp2cad part of the plugin.
