### ISSUE TITLE
Trelis plugin installation

### ISSUE THREAD

**Issue by liangjg** [svalinn/DAGMC-Trelis#57]
I failed to install trelis-plugins. Wondering if anyone ever encountered the same issue.
 - system: Ubuntu 18.04
- Trelis: both pro 17.0 and pro 16.5 from [Coreform Trelis Trial](https://csimsoft.com/trialTrelis)
Firstly, we tried the [distributions](https://uwmadison.app.box.com/v/dagmc-trelis), but apparently the Trelis-plugin is not loading:
```
Trelis>export dagmc geometry.h5m faceting_tolerance 1.0e-4
ERROR:
  Could not export the data to a file.
ERROR:
  is not a valid type of file to be exported.
```
- Then we tried to install the plugin from the source, but in the step to build the plugin:

```
>cmake .. -DCMAKE_PREFIX_PATH=/opt/Trelis-16.5/bin -DBUILD_MCNP_IMPORTER=OFF
CMake Error at CMakeLists.txt:10 (find_package):
  Found package configuration file:

    /opt/Trelis-16.5/bin/CubitConfig.cmake

  but it set Cubit_FOUND to FALSE so package "Cubit" is considered to be NOT
  FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  showviz_base



-- Configuring incomplete, errors occurred!
```
Any thoughts/suggestions? Thanks.

**Comment by makeclean** [comment]
The sbowviz base I can help with, remove mentions of those from the *.cmake files in the Trellis bin directories, then it should build
________________________________

**Comment by liangjg** [comment]
@makeclean Thanks for your advice. It works (though not sure if deleting the 'showviz_base' will affect the functionality). I'm closing this issue but do expect someone will update the [plugin distributions](https://uwmadison.app.box.com/v/dagmc-trelis) for newer versions of Cubit/Trelis.

**Comment by makeclean** [comment]
I suspect that its on the todo list - this particular issue is upstream in Trelis

On 23 Apr 2020, at 10:28, Jingang Liang <notifications@github.com<mailto:notifications@github.com>> wrote:



@makeclean<https://github.com/makeclean> Thanks for your advice. It works (though not sure if deleting the 'showviz_base' will affect the functionality). I'm closing this issue but do expect someone will update the plugin distributions<https://uwmadison.app.box.com/v/dagmc-trelis> for newer versions of Cubit/Trelis.

**Comment by gonuke** [comment]
Thanks for reporting this @liangjg 

We were not aware of a new Trelis version, yet, but we'll look into it soon.
