### ISSUE TITLE
cmake option should be  -DCUBIT_ROOT    instead of  -CUBIT_ROOT

### ISSUE THREAD

**Issue by qingfengxia** [svalinn/DAGMC-Trelis#67]
cmake ../Trelis-plugin -CUBIT_ROOT=/opt/Trelis-17.1 \

**Comment by ljacobson64** [comment]
Great catch, you are correct. I will submit a PR to fix this

**Comment by qingfengxia** [comment]
thank you,  I fixed my silly error when installing SDK, now it compiled.

**Comment by pshriwise** [comment]
This had been addressed by #68. Thanks for reporting it @qingfengxia!
