### ISSUE TITLE
inconsistencies between Trelis 17.1 and 16.5

### ISSUE THREAD

**Issue by bam241** [svalinn/DAGMC-Trelis#70]
I just found out issues with building the plugin with 16.5.

SDK are not packeted the same way (`Trelis/bin` vs `bin/`)

`find_package(Cubit REQUIRED CONFIG)` do not work
I had to use:
`find_package(Cubit)` instead
(It still complained that Cubit was not found, but the plugin I build was working anyway....

**Comment by bam241** [comment]
here is the error I see:
```
CMake Error at CMakeLists.txt:40 (find_package):
  Found package configuration file:

    /opt/Trelis-16.5/bin/CubitConfig.cmake

  but it set Cubit_FOUND to FALSE so package "Cubit" is considered to be NOT
  FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  showviz_base



-- Configuring incomplete, errors occurred!
````

**Comment by makeclean** [comment]
The .cmake files are broken, this was true in trelis 16.5 too, if you remove showviz from the offending .cmake files it will work fine
________________________________

**Comment by pshriwise** [comment]
Indeed. We got this sorted out this morning. There's also a provided note from @ljacobson64 in the README on this. I think that's the best we can do for now. Closing...
