### ISSUE TITLE
Build DAGMC export plugin for Windows

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC-Trelis#8]
Based on the recent success of building the plugin for MacOS, we should try to build a Windows plugin soon. I think most of the pieces are in place.
- [ ] build a sample/example plugin (no MOAB or HDF5 necessary)
- [ ] build (or install?) HDF5 for Windows
- [ ] build MOAB for Windows
- [ ] build plugin....

**Comment by gonuke** [comment]
This is perhaps complete - @ejwilson3 ?

**Comment by ejwilson3** [comment]
I think it is.
