### ISSUE TITLE
How to export in 'cm'?

### ISSUE THREAD

**Issue by thuDJ** [svalinn/DAGMC-Trelis#95]
Some Monte Carlo codes' default length unit is 'cm', while Trelis's default unit is 'mm'.

How can I export dagmc file in 'cm'?

**Comment by gonuke** [comment]
Trelis doesn't really have a default unit.  You can build models in Trelis/Cubit in any units.  If you import a model from some other CAD package, that package may have a default unit of `mm` that gets carried forward into Trelis/Cubit.

If you find yourself in this case, one option is to scale the entire model in Cubit by a factor of 10.  I think the command is something like:
`vol all scale 0.1`
You'll want to imprint and merge after performing this scaling operation.

**Comment by thuDJ** [comment]
Thanks a lot. I was in that case.

**Comment by shimwell** [comment]
Thanks for letting us know it worked, I shall close this issue now but feel free to reopen if the problem persists.
